<a href="https://colab.research.google.com/github/javmohir/python_darslari/blob/main/birinchi_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np
import pandas as pd
from pandas import DataFrame

In [3]:
data={'yil':[2021,2020,2019,2018,2017,2016,2015,2010],
      'aholi soni':[33.9,33.5,32.9,32.5,31.9,31.4,30.9,28.5],
      'temp':[1.54,1.64,1.49,1.53,1.63,1.54,1.48,1.65],
      'zichlik':[72.3,74.5,73.8,77.5,68.9,68.4,79.2,45.8]}

In [4]:
df=pd.DataFrame(data)
df

yil  aholi soni  temp  zichlik
0  2021        33.9  1.54     72.3
1  2020        33.5  1.64     74.5
2  2019        32.9  1.49     73.8
3  2018        32.5  1.53     77.5
4  2017        31.9  1.63     68.9
5  2016        31.4  1.54     68.4
6  2015        30.9  1.48     79.2
7  2010        28.5  1.65     45.8

In [5]:
df.index=[21,20,19,18,17,16,15,10]
df

yil  aholi soni  temp  zichlik
21  2021        33.9  1.54     72.3
20  2020        33.5  1.64     74.5
19  2019        32.9  1.49     73.8
18  2018        32.5  1.53     77.5
17  2017        31.9  1.63     68.9
16  2016        31.4  1.54     68.4
15  2015        30.9  1.48     79.2
10  2010        28.5  1.65     45.8

In [6]:
#reindex
ind=[21,20,19,18,17,16,15,10]
ind.sort()
ind

[10, 15, 16, 17, 18, 19, 20, 21]

In [7]:
df0=df.reindex(ind)
df0

yil  aholi soni  temp  zichlik
10  2010        28.5  1.65     45.8
15  2015        30.9  1.48     79.2
16  2016        31.4  1.54     68.4
17  2017        31.9  1.63     68.9
18  2018        32.5  1.53     77.5
19  2019        32.9  1.49     73.8
20  2020        33.5  1.64     74.5
21  2021        33.9  1.54     72.3

In [17]:
df1=df.drop(10, axis=0)
df1

yil  aholi soni  temp  zichlik
21  2021        33.9  1.54     72.3
20  2020        33.5  1.64     74.5
19  2019        32.9  1.49     73.8
18  2018        32.5  1.53     77.5
17  2017        31.9  1.63     68.9
16  2016        31.4  1.54     68.4
15  2015        30.9  1.48     79.2

In [19]:
df.drop([15,21])

yil  aholi soni  temp  zichlik
20  2020        33.5  1.64     74.5
19  2019        32.9  1.49     73.8
18  2018        32.5  1.53     77.5
17  2017        31.9  1.63     68.9
16  2016        31.4  1.54     68.4
10  2010        28.5  1.65     45.8

In [20]:
df.drop('yil',axis=1)

aholi soni  temp  zichlik
21        33.9  1.54     72.3
20        33.5  1.64     74.5
19        32.9  1.49     73.8
18        32.5  1.53     77.5
17        31.9  1.63     68.9
16        31.4  1.54     68.4
15        30.9  1.48     79.2
10        28.5  1.65     45.8

In [22]:
df.drop('yil',axis='columns')

aholi soni  temp  zichlik
21        33.9  1.54     72.3
20        33.5  1.64     74.5
19        32.9  1.49     73.8
18        32.5  1.53     77.5
17        31.9  1.63     68.9
16        31.4  1.54     68.4
15        30.9  1.48     79.2
10        28.5  1.65     45.8

In [23]:
df

yil  aholi soni  temp  zichlik
21  2021        33.9  1.54     72.3
20  2020        33.5  1.64     74.5
19  2019        32.9  1.49     73.8
18  2018        32.5  1.53     77.5
17  2017        31.9  1.63     68.9
16  2016        31.4  1.54     68.4
15  2015        30.9  1.48     79.2
10  2010        28.5  1.65     45.8

In [24]:
df_new=df.drop('yil',axis='columns')

In [25]:
df_new

aholi soni  temp  zichlik
21        33.9  1.54     72.3
20        33.5  1.64     74.5
19        32.9  1.49     73.8
18        32.5  1.53     77.5
17        31.9  1.63     68.9
16        31.4  1.54     68.4
15        30.9  1.48     79.2
10        28.5  1.65     45.8

In [ ]:
df.reindex([21,20,15,10])

yil  aholi soni  temp  zichlik
yil                                 
21   2021        33.9  1.54     72.3
20   2020        33.5  1.64     74.5
15   2015        30.9  1.48     79.2
10   2010        28.5  1.65     45.8

In [ ]:
df.reindex(index=range(10,21),method='ffill')

yil  aholi soni  temp  zichlik
yil                                 
10   2010        28.5  1.65     45.8
11   2010        28.5  1.65     45.8
12   2010        28.5  1.65     45.8
13   2010        28.5  1.65     45.8
14   2010        28.5  1.65     45.8
15   2015        30.9  1.48     79.2
16   2016        31.4  1.54     68.4
17   2017        31.9  1.63     68.9
18   2018        32.5  1.53     77.5
19   2019        32.9  1.49     73.8
20   2020        33.5  1.64     74.5

In [ ]:
df0=df.reindex(columns=['aholi soni','temp','zichlik'])
df0.sample(3)

aholi soni  temp  zichlik
yil                           
15         30.9  1.48     79.2
17         31.9  1.63     68.9
18         32.5  1.53     77.5

In [ ]:
df.loc[[21,18,15],['aholi soni','temp','zichlik']]

aholi soni  temp  zichlik
yil                           
21         33.9  1.54     72.3
18         32.5  1.53     77.5
15         30.9  1.48     79.2

In [ ]:
import pandas as pd


In [ ]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df2=pd.DataFrame(data)

In [ ]:
df2

Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [ ]:
df2.index.name='Yil'

In [ ]:
'Uzbekistan' in df2.columns

True

In [ ]:
2021 in df2.index

True

In [ ]:
df2.index

Int64Index([2021, 2020, 2019, 2018, 2017, 2016], dtype='int64', name='Yil')

In [ ]:
eliment=df2.index

In [ ]:
eliment

Int64Index([2021, 2020, 2019, 2018, 2017, 2016], dtype='int64', name='Yil')

In [ ]:
eliment[0]

2021

In [ ]:
eliment[1:4]

Int64Index([2020, 2019, 2018], dtype='int64', name='Yil')

In [ ]:
df2.columns

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

In [ ]:
df2.head()

Uzbekistan  Kazakhstan
Yil                         
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1

In [ ]:
df2=pd.DataFrame(data, index=[2021,2020,2018])

In [ ]:
df2

Uzbekistan  Kazakhstan
Yil                         
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [ ]:
df2.index.name='yil'

In [ ]:
df2

Uzbekistan  Kazakhstan
yil                         
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [ ]:
df2.index

Int64Index([2021, 2020, 2019, 2018, 2017, 2016], dtype='int64', name='yil')

In [ ]:
df2.T

yil         2021  2020  2019  2018  2017  2016
Uzbekistan  33.9  33.5  32.9  32.5  31.9   NaN
Kazakhstan  18.9  18.7  18.5  18.3  18.1  17.8

In [ ]:
arr=df2.values

In [ ]:
arr

array([[33.9, 18.9],
       [33.5, 18.7],
       [32.9, 18.5],
       [32.5, 18.3],
       [31.9, 18.1],
       [ nan, 17.8]])

In [ ]:
df2.columns

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

In [ ]:
'tojikiston' in df2.columns

False

In [ ]:
2020 in df2.index

True

In [ ]:
indes=df2.index

In [ ]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}
data={'username':usernames,
      'email':emails}
df=pd.DataFrame(data)

In [ ]:
df

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com

In [ ]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}


In [ ]:
df1=df.append(pd.DataFrame(data2))

In [ ]:
df1

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
df1.index

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
newind=pd.Index(['nafisa','guzal','olim'])
newind

Index(['nafisa', 'guzal', 'olim'], dtype='object')

In [ ]:
newind.isin(df1.index)

array([False, False,  True])

In [ ]:
df1.index.difference(newind)

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [ ]:
df1.index.union(newind)

Index(['anvar', 'guzal', 'javohir', 'maryam', 'maryam', 'nafisa', 'olim',
       'olim'],
      dtype='object')

In [ ]:
df1.index.delete(0)

Index(['olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
df1.index.drop('olim')

Index(['anvar', 'maryam', 'javohir', 'maryam'], dtype='object')

In [ ]:
df1.index

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
df1.index.insert(3,'masha')

Index(['anvar', 'olim', 'maryam', 'masha', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
df.head()

NameError: ignored

In [ ]:
df.index

NameError: ignored

In [ ]:
df=pd.DataFrame(data, columns=['yil','temp','aholi soni'])

In [ ]:
df.head()

yil  temp  aholi soni
0  2021  1.54        33.9
1  2020  1.48        33.5
2  2019  1.56        32.9
3  2018  1.62        32.5
4  2017  1.65        31.9

In [ ]:
df=pd.DataFrame(data, columns=['yil','temp','aholi soni','yim'], index=[21,20,19,18,17,16,15,10])

NameError: ignored

In [ ]:
df.head()

yil  temp  aholi soni  yim
21  2021  1.54        33.9  NaN
20  2020  1.48        33.5  NaN
19  2019  1.56        32.9  NaN
18  2018  1.62        32.5  NaN
17  2017  1.65        31.9  NaN

In [ ]:
df['aholi soni']

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: aholi soni, dtype: float64

In [ ]:
aholi=df['aholi soni']

In [ ]:
df=pd.DataFrame(data, columns=['yil','temp','aholi soni','yim'], index=['bir','ikki','uch','turt','besh','olti','yetti'])

ValueError: ignored

In [ ]:
aholi

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: aholi soni, dtype: float64

In [ ]:
type(aholi)

pandas.core.series.Series

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(8, 3)

In [ ]:
from pandas import Series # seris malumotlar tuzilmasi

In [ ]:
obj=Series([4,5,6,-6.5])

In [ ]:
type(obj)

pandas.core.series.Series

In [ ]:
print(obj)

0    4.0
1    5.0
2    6.0
3   -6.5
dtype: float64


In [ ]:
obj.values

array([ 4. ,  5. ,  6. , -6.5])

In [ ]:
cars={'tiko':1900,'malibu':35000,'lasette':12000}

In [ ]:
cars1=Series(cars)

In [ ]:
cars1

tiko        1900
malibu     35000
lasette    12000
dtype: int64

In [ ]:
'tiko' in cars1



True

In [ ]:
'jentra' in cars1

In [ ]:
models=['cobalt','lasette','malibu','not','tiko']

In [ ]:
cars1=Series(cars,index=models)

In [ ]:
cars1

cobalt         NaN
lasette    12000.0
malibu     35000.0
not            NaN
tiko        1900.0
dtype: float64

In [ ]:
cars1.isnull()

cobalt      True
lasette    False
malibu     False
not         True
tiko       False
dtype: bool

In [ ]:
cars1.notnull

cobalt     False
lasette     True
malibu      True
not        False
tiko        True
dtype: bool